### ISSUE TITLE
Floop fails to kill child process

### ISSUE THREAD

**Issue by setcheverry** [d3sw/floop#12]
## Expected Behavior
When the Floop process is killed (by Nomad delete job API call) then the child processes should be killed too.

## Current Behavior
When the Floop process is killed (by Nomad delete job API call) then the child processes continues to execute even if the Floop process is no longer running.

## Possible Solution
Check child process kill signal?

## Steps to Reproduce (for bugs)
1. Start a long running process with Floop using nomad as a scheduler.
2. Once processing started send a Delete job command to nomad.
3. The child process will continue to run even if the Floop process is no longer running.

## Context
Trying to stop an Apple iTunes Transporter transfer using the Nomad API.

## Your Environment

* Product Version: v0.1.0
* OS and OS Version: CentOS release 6.9 (2.6.32-696.6.3.el6.x86_64)

**Comment by euforia** [comment]
This should be resolved with #13

**Comment by setcheverry** [comment]
This was verified and it now works.
