### ISSUE TITLE
Nats failed handler doesn't transform data

### ISSUE THREAD

**Issue by mark-parker** [d3sw/floop#25]
deluxe.checksum.status
{
  "Details": {
    "Code": 2,
    "Stdout": "RXJyb3I9b3BlbiBEOlxzdG9yYWdlXHN0YWdpbmdcVmF1bHRcbW92aWUubXBnMTogVGhlIHN5c3RlbSBjYW5ub3QgZmluZCB0aGUgZmlsZSBzcGVjaWZpZWQu",
    "Stderr": null
  },
  "status": "FAILED"
}

**Comment by euforia** [comment]
I'm closing this one as its related to #23
