### ISSUE TITLE
Add meta parameters to the documentation

### ISSUE THREAD

**Issue by toddschilling** [d3sw/floop#7]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
README or other docs should include an example where the configuration has required parameters and the command-line call passes them in to floop.

## Current Behavior
There are currently no examples showing how to use parameters.

## Possible Solution
Update the README, fool!

## Your Environment
Sunny Southern California.

**Comment by euforia** [comment]
Fixed by #8
