### ISSUE TITLE
Service discovery for Floop

### ISSUE THREAD

**Issue by setcheverry** [d3sw/floop#9]
## Expected Behavior
Floop should be able to use service discovery. The configuration should have a flag that indicates if service discovery is needed for the domain to where floop needs to send the state of a job.

## Current Behavior
Floop doesn't support service discovery.

## Possible Solution
Use https://github.com/euforia/go-srv-resolver to add this functionality to floop.

## Context
When a service to report to is deployed using Docker then it URI will change over time. By adding service discovery to Floop, it will be able to report progress even if the uri of the service changes.

## Your Environment
* Product Version: v0.1.0
* OS and OS Version: CentOS release 6.9 (2.6.32-696.6.3.el6.x86_64)

**Comment by euforia** [comment]
We could add a top level config variable or just use DNS based service discovery by default and revert back to using regular DNS queries in the event of failure.  Any thoughts?

**Comment by toddschilling** [comment]
I was thinking about that too.  At first I thought we'd use a configuration variable, but adding configuration when we don't need to might make the product overly complex to use in the long run.  I think maybe just use DNS to do an SRV query and automatically revert to an A query if SRV doesn't return anything.

**Comment by metroidprototype** [comment]
resolved with PR #11
